application: arenaplanner
version: 2014s
runtime: python27
api_version: 1
threadsafe: true

libraries:
- name: django
  version: "1.2"

handlers:
- url: /static
  static_dir: static
- url: /.*
  script: ap.application
